# Generated by Django 5.0.6 on 2024-05-11 21:20

from django.db import migrations


def populate_roles_teams(apps, schemaeditor):
    
    roles = {
        'Developer': 'The person on the team who works on the issues',
        'Product Owner': 'The person on the team who writes issues',
        'Scrum Master': 'The teams coach',
    }
    teams = {
        'alpha': 'The A team',
        'Bravo': 'The B team',
        'Charlie': 'The C team',
    }

    Role = apps.get_model('accounts', 'Role')
    Team = apps.get_model('accounts', 'Team')

    for key, value in roles.items():
        role_obj = Role(name=key, description=value)
        role_obj.save()

    for key, value in teams.items():
        team_obj = Team(name=key, description=value)
        team_obj.save()




class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_roles_teams)
    ]
